### PR TITLE
Add Vietnamese translations

### PR DESCRIPTION
**Pull request by wolf20482**

### CODE REVIEW

**Review by RTa-technology — CHANGES_REQUESTED** [review]
If you have an editor that can do regular expression substitutions, could you please convert them in this way?

`top.ftml`
```ftml
[[ul]]
[[li]][# Rules][[ul]]
[[li]][[[Site Rules]]][[/li]]
[[/ul]][[/li]]
[[/ul]]
```

```
\s\*\s(.+) => [[li]]$1[[/li]]
```
```
\*\s(.+) => 

[[/ul]][[/li]]
[[/ul]][[ul]]
[[li]]$1[[ul]] 

and Initial 

[[/ul]][[/li]]
[[/ul]] 

at the end

\[\[li\]\](.+)\[\[ul\]\] => [[li]][# $1][[ul]]

```
For some reason, it does not work well with Wd's nested list.

**Comment by wolf20482** [comment]
I have VS code so it probably can do that, let me try

**Comment by RTa-technology** [comment]
thank you!

**Comment by wolf20482** [comment]
also what do you mean with the `=>` things? I tried to find with the regexes before the `=>` things, it doesn't work

**Comment by RTa-technology** [comment]
A=>B means that A is replaced by B.
Sorry, the readme will modify to make it clearer.

**Comment by wolf20482** [comment]
I used regex101.com's ECMAScript regex flavor to make changes, please check if I've done everything right

**Comment by RTa-technology** [comment]
I think I have probably converted side.ftml (on top.ftml).

**Comment by RTa-technology** [comment]
Can I fix it?

**Comment by wolf20482** [comment]
> I think I have probably converted side.ftml (on top.ftml).

what do you mean?

**Comment by wolf20482** [comment]
I forgot to re-request btw

**Comment by RTa-technology** [comment]
> > I think I have probably converted side.ftml (on top.ftml).
>
> what do you mean?

I think you pasted the contents of side.ftml into top.ftml and replaced it.

**Comment by wolf20482** [comment]
oh that's right, I pasted the wrong thing in

**Comment by wolf20482** [comment]
I edited it, sorry for that

**Comment by RTa-technology** [comment]
thank you!

**Review by RTa-technology — APPROVED** [review]

**Review by RTa-technology — APPROVED** [review]

**Pull request merged**
